### ISSUE TITLE
TODOs for @ffleurey

### ISSUE THREAD

**Issue by brice-morin** [HEADS-project/methodology#5]
Contribute [here](https://github.com/HEADS-project/methodology/blob/master/heads_methodology/extend_the_thingml_transformations_to_compile_code_for_a_new_platform.md#message-queuing--scheduling--dispatch)

**Comment by ffleurey** [comment]
OK, I pushed something. mostly focussing on the C compiler because for the others it is not such an issue

**Comment by brice-morin** [comment]
Yes, makes sense, that is why I could'nt really write it
